services:
  - memcached

language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - |
    pecl info apcu >/dev/null 2>&1 && printf "extension=apcu.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/apcu.ini
    pecl info apcu >/dev/null 2>&1 || yes '' | pecl install "apcu${APCU_VERSION+"-"}${APCU_VERSION:-""}"
    printf "[apcu]\napc.enabled=1\napc.enable_cli=1\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/apcu.ini
    phpenv config-add ~/.phpenv/versions/$(phpenv version-name)/etc/apcu.ini
  - phpenv rehash
  - php -i

install: composer install

script: ./vendor/bin/phpunit -v --coverage-text --exclude-group requires-separate-process,ldap_integration -c phpunit.travis.xml
