version: "3"
services:
  php70:
    build: docker/php70/
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - memcached
      - ldap

  php71:
    build: docker/php71/
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - memcached
      - ldap

  php72:
    build: docker/php72/
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - memcached
      - ldap

  php73:
    build: docker/php73/
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      - memcached
      - ldap

  memcached:
    image: memcached
    networks:
      - mynetwork

  ldap:
    image: osixia/openldap
    volumes:
      - ./tests/assets/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    ports:
      - 3890:389
    networks:
      - mynetwork

networks:
  mynetwork: